### ISSUE TITLE
Testing the plugin for sentry hosted behing VPN

### ISSUE THREAD

**Issue by kubijo** [nhat-phan/sentry-integration#2]
Hi. I've just started testing the plugin on our testing sentry, that is hidden behind VPN (if that is of some importance) and I'm getting these on following pycharm installation...

```
PyCharm 2020.3.3 (Professional Edition)
Build #PY-203.7148.72, built on January 27, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-43-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: terminal.buffer.max.lines.count=10000, documentation.show.toolbar=true, debugger.watches.in.variables=false, ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0, jest.test.tree.use.jasmine.reporter=false
Non-Bundled Plugins: Dummy Text Generator, com.alayouni.ansiHighlight, com.andrey4623.rainbowcsv, com.fwdekker.randomness, com.github.camork.fileExpander, com.github.leomillon.uuidgenerator, com.intellij.ideolog, de.achimonline.tempconfigcleaner, indent-rainbow.indent-rainbow, io.github.qeesung.component.HighlightBracketPair, lermitage.intellij.extra.icons, lermitage.intellij.iconviewer, net.ntworld.nhat-phan.sentry-integration, net.vektah.codeglance, zielu.gittoolbox, mobi.hsz.idea.gitignore, com.jetbrains.codeWithMe, name.kropp.intellij.makefile, org.toml.lang, shorty.mnemonic, NodeJS, cucumber-javascript, intellij.prettierJS, com.intellij.lang.jsgraphql, izhangzhihao.rainbow.brackets, com.github.lppedd.idea-return-highlighter, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements, org.rust.lang
Current Desktop: ubuntu:GNOME
```

```
java.lang.NumberFormatException: For input string: "1611619200.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeInt(StreamingJsonInput.kt:106)
	at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:76)
	at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:72)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at kotlinx.serialization.internal.ListLikeSerializer.readItem(CollectionSerializers.kt:98)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readItem$default(CollectionSerializers.kt:70)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at kotlinx.serialization.internal.ListLikeSerializer.readItem(CollectionSerializers.kt:98)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readItem$default(CollectionSerializers.kt:70)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at net.ntworld.sentryIntegration.client.parser.raw.IssueDetailStatsRaw$$serializer.deserialize(IssueDetailStatsRaw.kt)
	at net.ntworld.sentryIntegration.client.parser.raw.IssueDetailStatsRaw$$serializer.deserialize(IssueDetailStatsRaw.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at net.ntworld.sentryIntegration.client.parser.raw.IssueDetailRaw$$serializer.deserialize(IssueDetailRaw.kt)
	at net.ntworld.sentryIntegration.client.parser.raw.IssueDetailRaw$$serializer.deserialize(IssueDetailRaw.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.CoreKt.decode(Core.kt:79)
	at kotlinx.serialization.json.Json.parse(Json.kt:152)
	at net.ntworld.sentryIntegration.client.parser.SentryIssueParser.parseIssueDetail(SentryIssueParser.kt:45)
	at net.ntworld.sentryIntegration.client.SentryApiImpl.getIssueDetail(SentryApiImpl.kt:126)
	at net.ntworld.sentryIntegration.client.CacheSentryApi.getIssueDetail(CacheSentryApi.kt:38)
	at net.ntworld.sentryIntegrationIdea.task.FetchIssueDetailTask.run(FetchIssueDetailTask.kt:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kubijo** [comment]
The project loads and shows exceptions, but details are not shown, and I can't navigate to the code… I don't know if the configuration is correct because there doesn't seem to be a hint on the type of path that is supposed to go into the `deployed path` field, but I'm presuming that it's a relative path to repository root, so I've given it just a directory name

![image](https://user-images.githubusercontent.com/11244314/109140805-48160a80-775d-11eb-9608-4dee6e8184c2.png)

**Comment by fan-tom** [comment]
I suppose it is issue with stats parsing. GET /issuses/{id} returns `stats` object that has `30d` and `24d` fields, that are arrays of tuples with valus like `[ 1620691200, 0 ]`, which is similar to the number in exception.
